use crate::loom::cell::UnsafeCell;
use crate::loom::sync::atomic::{AtomicPtr, AtomicUsize};

use std::alloc::Layout;
use std::mem::MaybeUninit;
use std::ops;
use std::ptr::{self, NonNull};
use std::sync::atomic::Ordering::{self, AcqRel, Acquire, Release};

/// A block in a linked list.
///
/// Each block in the list can hold up to `BLOCK_CAP` messages.
pub(crate) struct Block<T> {
    /// The header fields.
    header: BlockHeader<T>,

    /// Array containing values pushed into the block. Values are stored in a
    /// continuous array in order to improve cache line behavior when reading.
    /// The values must be manually dropped.
    values: Values<T>,
}

/// Extra fields for a `Block<T>`.
struct BlockHeader<T> {
    /// The start index of this block.
    ///
    /// Slots in this block have indices in `start_index .. start_index + BLOCK_CAP`.
    start_index: usize,

    /// The next block in the linked list.
    next: AtomicPtr<Block<T>>,

    /// Bitfield tracking slots that are ready to have their values consumed.
    ready_slots: AtomicUsize,

    /// The observed `tail_position` value *after* the block has been passed by
    /// `block_tail`.
    observed_tail_position: UnsafeCell<usize>,
}

pub(crate) enum Read<T> {
    Value(T),
    Closed,
}

#[repr(transparent)]
struct Values<T>([UnsafeCell<MaybeUninit<T>>; BLOCK_CAP]);

use super::BLOCK_CAP;

/// Masks an index to get the block identifier.
const BLOCK_MASK: usize = !(BLOCK_CAP - 1);

/// Masks an index to get the value offset in a block.
const SLOT_MASK: usize = BLOCK_CAP - 1;

/// Flag tracking that a block has gone through the sender's release routine.
///
/// When this is set, the receiver may consider freeing the block.
const RELEASED: usize = 1 << BLOCK_CAP;

/// Flag tracking all senders dropped.
///
/// When this flag is set, the send half of the channel has closed.
const TX_CLOSED: usize = RELEASED << 1;

/// Mask covering all bits used to track slot readiness.
const READY_MASK: usize = RELEASED - 1;

/// Returns the index of the first slot in the block referenced by `slot_index`.
#[inline(always)]
pub(crate) fn start_index(slot_index: usize) -> usize {
    BLOCK_MASK & slot_index
}

/// Returns the offset into the block referenced by `slot_index`.
#[inline(always)]
pub(crate) fn offset(slot_index: usize) -> usize {
    SLOT_MASK & slot_index
}

generate_addr_of_methods! {
    impl<T> Block<T> {
        unsafe fn addr_of_header(self: NonNull<Self>) -> NonNull<BlockHeader<T>> {
            &self.header
        }

        unsafe fn addr_of_values(self: NonNull<Self>) -> NonNull<Values<T>> {
            &self.values
        }
    }
}

impl<T> Block<T> {
    pub(crate) fn new(start_index: usize) -> Box<Block<T>> {
        // SAFETY: This block performs four unsafe operations; each is justified inline
        // below. Taken together they construct a `Block<T>` on the heap and hand exclusive
        // ownership of it to a `Box`, so on return no raw pointer to the allocation
        // survives and there is exactly one owner responsible for deallocating it.
        unsafe {
            // Allocate the block on the heap.
            // SAFETY:
            // Contract from `std::alloc::alloc`: the layout must have non-zero size, and
            // the returned pointer is either null or points to a fresh allocation of that
            // layout whose contents are uninitialized.
            // Evidence: `Block<T>` embeds `BlockHeader<T>`, which contains a `usize`
            // `start_index`, so `size_of::<Block<T>>() >= size_of::<usize>() > 0`
            // regardless of `T`. The null case is handled immediately below.
            let block = std::alloc::alloc(Layout::new::<Block<T>>()) as *mut Block<T>;
            let block = match NonNull::new(block) {
                Some(block) => block,
                None => std::alloc::handle_alloc_error(Layout::new::<Block<T>>()),
            };

            // Write the header to the block.
            // SAFETY:
            // Two operations.
            // 1. `Block::addr_of_header(block)` — generated by `generate_addr_of_methods!`,
            //    which expands to `&raw mut (*block).header`. Its contract is that `block`
            //    points to an allocation large enough and aligned for `Block<T>`; that is
            //    exactly what the `alloc` above returned (the allocation need not be
            //    initialized, since the macro forms a raw pointer without creating an
            //    intermediate reference). The result is non-null and aligned for
            //    `BlockHeader<T>`.
            // 2. `.write(..)` — contract from `ptr::write`: the destination must be
            //    non-null, aligned, and valid for writes; it need not be initialized, and
            //    the old contents are *not* dropped. Evidence: (1) gives non-null and
            //    aligned, the allocation is live and large enough, and its contents are
            //    fresh uninitialized bytes, so there is no old value to drop. This is the
            //    only writer: the allocation has not yet been published anywhere.
            // Postcondition: `(*block).header` holds an initialized `BlockHeader<T>`.
            Block::addr_of_header(block).as_ptr().write(BlockHeader {
                // The absolute index in the channel of the first slot in the block.
                start_index,

                // Pointer to the next block in the linked list.
                next: AtomicPtr::new(ptr::null_mut()),

                ready_slots: AtomicUsize::new(0),

                observed_tail_position: UnsafeCell::new(0),
            });

            // Initialize the values array.
            // SAFETY:
            // Two operations.
            // 1. `Block::addr_of_values(block)` — as for `addr_of_header` above, this
            //    expands to `&raw mut (*block).values` and needs only that `block` point
            //    to an allocation laid out for `Block<T>`.
            // 2. `Values::initialize(..)` — contract: the pointer must be valid for
            //    writing a `Values<T>`. Evidence: (1) yields a non-null, aligned pointer
            //    into the live allocation just obtained, and nothing else can reach it.
            // Note on what this leaves behind: outside `loom` this call is a no-op, which
            // is sound because `Values<T>` is `#[repr(transparent)]` over
            // `[UnsafeCell<MaybeUninit<T>>; BLOCK_CAP]`. `UnsafeCell<U>` has the same
            // in-memory representation as `U` (std docs) and `MaybeUninit<T>` imposes no
            // validity requirement on its bytes (std docs), so an array of them is a valid
            // value at its type even when every byte is uninitialized. Consequently the
            // `&Values<T>` produced later by `Index` is a valid reference.
            Values::initialize(Block::addr_of_values(block));

            // Convert the pointer to a `Box`.
            // SAFETY:
            // Contract from `Box::from_raw`: the pointer must be non-null, properly
            // aligned, point to a valid initialized `Block<T>`, and have come from the
            // global allocator with the layout `Box` will use to free it — and the caller
            // must give up all other access to the allocation.
            // Evidence:
            // - Non-null: checked by the `NonNull::new` match above.
            // - Allocator and layout: allocated just above by `std::alloc::alloc` with
            //   `Layout::new::<Block<T>>()`, which is the layout `Box<Block<T>>` uses to
            //   deallocate. Alignment follows from that layout.
            // - Validity: `header` was initialized by the `write` above, and `values` is
            //   valid uninitialized as argued in the note above, so the whole `Block<T>`
            //   is a valid value at its type.
            // - Ownership: `block` is a local that is not used after this point, and the
            //   allocation has not been published, so the returned `Box` is the unique
            //   owner and will deallocate exactly once.
            Box::from_raw(block.as_ptr())
        }
    }

    /// Returns `true` if the block matches the given index.
    pub(crate) fn is_at_index(&self, index: usize) -> bool {
        debug_assert!(offset(index) == 0);
        self.header.start_index == index
    }

    /// Returns the number of blocks between `self` and the block at the
    /// specified index.
    ///
    /// `start_index` must represent a block *after* `self`.
    pub(crate) fn distance(&self, other_index: usize) -> usize {
        debug_assert!(offset(other_index) == 0);
        other_index.wrapping_sub(self.header.start_index) / BLOCK_CAP
    }

    /// Reads the value at the given offset.
    ///
    /// Returns `None` if the slot is empty.
    ///
    /// # Safety
    ///
    /// To maintain safety, the caller must ensure:
    ///
    /// * No concurrent access to the slot identified by `slot_index`, for the whole
    ///   duration of the call. In this channel that is guaranteed by there being a single
    ///   receiver, which is the only caller of this method.
    /// * `slot_index` belongs to this block, i.e. `offset(slot_index)` is a slot of
    ///   `self`. (`offset` masks the index, so an out-of-block index silently aliases
    ///   another slot rather than panicking.)
    ///
    /// # Postcondition
    ///
    /// If `Some(Read::Value(_))` is returned, the value has been *moved out* of the slot
    /// by a bitwise copy: the slot's bytes are unchanged but no longer own a `T`. The
    /// caller must never read the same slot again, or the `T` would be duplicated and
    /// dropped twice. In this channel the receiver advances `rx_fields.index` past the
    /// slot before any subsequent read, and the block's ready bit is never cleared, so
    /// each slot is read at most once.
    pub(crate) unsafe fn read(&self, slot_index: usize) -> Option<Read<T>> {
        let offset = offset(slot_index);

        let ready_bits = self.header.ready_slots.load(Acquire);

        if !is_ready(ready_bits, offset) {
            if is_tx_closed(ready_bits) {
                return Some(Read::Closed);
            }

            return None;
        }

        // Get the value
        //
        // SAFETY:
        // Operation: `ptr::read(ptr)` where `ptr: *const MaybeUninit<T>`.
        // Contract from `ptr::read`: `ptr` must be non-null, properly aligned, valid for
        // reads of `size_of::<MaybeUninit<T>>()` bytes, and point to a valid value at that
        // type.
        // Evidence:
        // - `UnsafeCell::with` yields a non-null, aligned pointer to the cell's contents,
        //   and the block is live because `&self` borrows it.
        // - The value read is a `MaybeUninit<T>`, which is a valid value for *any* byte
        //   pattern (std docs), so no initialization premise is needed for this step.
        // - No concurrent access: this method's `# Safety` precondition. The sender's
        //   write to this slot happened-before us: `is_ready` above observed the slot's
        //   bit in an `Acquire` load, which synchronizes with the `Release` `fetch_or` in
        //   `set_ready` that the sender performs after `ptr::write`.
        // Postcondition: this is a bitwise copy, so the slot must not be read again — see
        // this method's documented postcondition.
        let value = self.values[offset].with(|ptr| unsafe { ptr::read(ptr) });

        // SAFETY:
        // Contract from `MaybeUninit::assume_init`: the `MaybeUninit<T>` must be in an
        // initialized state holding a valid `T`.
        // Evidence: `is_ready(ready_bits, offset)` returned true above. The ready bit for
        // a slot is set only by `set_ready`, which `Block::write` calls *after*
        // `ptr::write(ptr, MaybeUninit::new(value))` has stored an owned `T`. The
        // `Acquire` load and `Release` `fetch_or` pair orders that write before this read,
        // so the bytes copied out above are those of an initialized `T`.
        // Postcondition: ownership of the `T` is now held by the returned `Read::Value`;
        // the slot no longer owns it.
        Some(Read::Value(unsafe { value.assume_init() }))
    }

    /// Returns true if *this* block has a value in the given slot.
    ///
    /// Always returns false when given an index from a different block.
    pub(crate) fn has_value(&self, slot_index: usize) -> bool {
        if slot_index < self.header.start_index {
            return false;
        }
        if slot_index >= self.header.start_index + super::BLOCK_CAP {
            return false;
        }

        let offset = offset(slot_index);
        let ready_bits = self.header.ready_slots.load(Acquire);
        is_ready(ready_bits, offset)
    }

    /// Writes a value to the block at the given offset.
    ///
    /// # Safety
    ///
    /// To maintain safety, the caller must ensure:
    ///
    /// * The slot identified by `slot_index` is empty — its ready bit is clear and it does
    ///   not own a `T`. Writing over an owned value would leak it, since `ptr::write` does
    ///   not drop the previous contents.
    /// * No concurrent access to that slot, for the whole duration of the call. In this
    ///   channel that is guaranteed by each sender claiming a unique `tail_position`
    ///   before calling this method, so no two senders target the same slot.
    /// * `slot_index` belongs to this block (`offset` masks the index, so an out-of-block
    ///   index silently aliases another slot).
    ///
    /// # Postcondition
    ///
    /// Ownership of `value` moves into the slot, and the slot's ready bit is set with
    /// `Release` ordering. **After this method returns the caller must not touch the block
    /// again**: publishing the ready bit permits the receiver to read the slot and, once
    /// the block is released, to free it.
    pub(crate) unsafe fn write(&self, slot_index: usize, value: T) {
        // Get the offset into the block
        let slot_offset = offset(slot_index);

        self.values[slot_offset].with_mut(|ptr| {
            // SAFETY:
            // Operation: `ptr::write(ptr, MaybeUninit::new(value))`.
            // Contract from `ptr::write`: the destination must be non-null, properly
            // aligned, and valid for writes. It does not require the destination to be
            // initialized and does not drop the old value.
            // Evidence:
            // - `UnsafeCell::with_mut` yields a non-null, aligned pointer to the cell's
            //   contents, and the block is live because `&self` borrows it.
            // - Exclusivity for the duration of the write is this method's `# Safety`
            //   precondition. The receiver may only read the slot after observing its
            //   ready bit, which `set_ready` publishes below.
            // - Not dropping the old value is correct here rather than a leak, because
            //   the precondition states the slot is empty.
            // Postcondition: the slot now owns `value`.
            unsafe {
                ptr::write(ptr, MaybeUninit::new(value));
            }
        });

        // Release the value. After this point, the slot ref may no longer
        // be used. It is possible for the receiver to free the memory at
        // any point.
        self.set_ready(slot_offset);
    }

    /// Signal to the receiver that the sender half of the list is closed.
    ///
    /// # Safety
    ///
    /// This method performs no memory-unsafe operation — its body is a single atomic
    /// `fetch_or` — so it imposes no memory-safety obligation on the caller and could be
    /// written as a safe function. It is marked `unsafe` only to flag the protocol
    /// obligation that the caller must be the sender half and must have established that
    /// no further sender will write to this block. Violating that is a logic error (the
    /// receiver may report the channel closed early); it cannot cause undefined behaviour.
    pub(crate) unsafe fn tx_close(&self) {
        self.header.ready_slots.fetch_or(TX_CLOSED, Release);
    }

    /// Resets the block to a blank state. This enables reusing blocks in the
    /// channel.
    ///
    /// # Safety
    ///
    /// To maintain safety, the caller must ensure:
    ///
    /// * All slots are empty.
    /// * The caller holds a unique pointer to the block.
    pub(crate) unsafe fn reclaim(&mut self) {
        self.header.start_index = 0;
        self.header.next = AtomicPtr::new(ptr::null_mut());
        self.header.ready_slots = AtomicUsize::new(0);
    }

    /// Releases the block to the rx half for freeing.
    ///
    /// This function is called by the tx half once it can be guaranteed that no
    /// more senders will attempt to access the block.
    ///
    /// # Safety
    ///
    /// To maintain safety, the caller must ensure:
    ///
    /// * The block will no longer be accessed by any sender, from the moment this call
    ///   begins and for the rest of the block's life. This gives the caller exclusive
    ///   access to `observed_tail_position` for the duration of the call, which is what
    ///   makes the non-atomic write below sound.
    ///
    /// # Postcondition
    ///
    /// `observed_tail_position` holds `tail_position` and the `RELEASED` bit is published
    /// with `Release` ordering. The receiver may free the block as soon as all slots prior
    /// to `observed_tail_position` have been filled, so **the caller must not touch the
    /// block after this call returns**.
    pub(crate) unsafe fn tx_release(&self, tail_position: usize) {
        // Track the observed tail_position. Any sender targeting a greater
        // tail_position is guaranteed to not access this block.
        self.header
            .observed_tail_position
            // SAFETY:
            // Operation: a non-atomic write of a `usize` through the cell.
            // Required contract: the pointer must be non-null, aligned and valid for
            // writes of `usize`, and no other thread may access the cell concurrently.
            // Evidence:
            // - `UnsafeCell::with_mut` yields a non-null, aligned pointer to the cell's
            //   contents, and the block is live because `&self` borrows it.
            // - Exclusivity is this method's `# Safety` precondition: no sender will touch
            //   the block again. The receiver reads this cell only from
            //   `observed_tail_position()`, and only after an `Acquire` load observes the
            //   `RELEASED` bit — which the `Release` `fetch_or` below publishes *after*
            //   this write, so the two are ordered and never concurrent.
            // - `usize` has no drop glue, so overwriting the previous value is a plain
            //   store with no ownership consequences.
            .with_mut(|ptr| unsafe { *ptr = tail_position });

        // Set the released bit, signalling to the receiver that it is safe to
        // free the block's memory as soon as all slots **prior** to
        // `observed_tail_position` have been filled.
        self.header.ready_slots.fetch_or(RELEASED, Release);
    }

    /// Mark a slot as ready
    fn set_ready(&self, slot: usize) {
        let mask = 1 << slot;
        self.header.ready_slots.fetch_or(mask, Release);
    }

    /// Returns `true` when all slots have their `ready` bits set.
    ///
    /// This indicates that the block is in its final state and will no longer
    /// be mutated.
    pub(crate) fn is_final(&self) -> bool {
        self.header.ready_slots.load(Acquire) & READY_MASK == READY_MASK
    }

    /// Returns the `observed_tail_position` value, if set
    pub(crate) fn observed_tail_position(&self) -> Option<usize> {
        if 0 == RELEASED & self.header.ready_slots.load(Acquire) {
            None
        } else {
            Some(
                self.header
                    .observed_tail_position
                    // SAFETY:
                    // Operation: reading the `usize` behind the `observed_tail_position`
                    // cell.
                    // Required contract: the pointer must be non-null, aligned, valid for
                    // reads of `usize`, point to an initialized value, and not be written
                    // concurrently.
                    // Evidence:
                    // - `UnsafeCell::with` yields a non-null, aligned pointer to the
                    //   cell's contents, and the block is live because `&self` borrows it.
                    // - Initialization: set to `0` in `Block::new` and only ever
                    //   overwritten with another `usize` by `tx_release`.
                    // - No concurrent writer: the only writer is `tx_release`, which
                    //   writes the cell and *then* sets `RELEASED` with a `Release`
                    //   `fetch_or`. The branch above only reaches this line after an
                    //   `Acquire` load observed `RELEASED`, which synchronizes with that
                    //   `Release` store; `tx_release`'s own contract says no sender
                    //   touches the block afterwards, so the write is complete and
                    //   visible, and no further write can occur.
                    .with(|ptr| unsafe { *ptr }),
            )
        }
    }

    /// Loads the next block
    pub(crate) fn load_next(&self, ordering: Ordering) -> Option<NonNull<Block<T>>> {
        let ret = NonNull::new(self.header.next.load(ordering));

        // SAFETY:
        // Operation: `block.as_ref()`, creating `&Block<T>` from the `next` pointer.
        // Required contract (from `NonNull::as_ref`): the pointer must be non-null (given
        // by `NonNull`), aligned, point to an initialized `Block<T>`, and that block must
        // stay live for the returned lifetime with no `&mut` alias.
        // Evidence:
        // - A non-null `next` was published by `try_push`/`grow`, which only ever store a
        //   pointer obtained from `Box::into_raw(Block::new(..))`, so it is aligned and
        //   points to a fully initialized `Block<T>`.
        // - Liveness: a block is only freed by the receiver, via `free_blocks` or
        //   `reclaim_block`, after it has been unlinked from the list reachable from
        //   `self`. Since `&self` borrows a block still in the list, its successor has not
        //   been freed. This debug assertion runs on the same thread that just loaded the
        //   pointer, with no intervening yield.
        // - Aliasing: blocks in the list are only ever reached through shared references
        //   and atomics; the sole `&mut Block<T>` (`reclaim`) requires unique ownership of
        //   an already-unlinked block.
        // The read itself is of `header.start_index`, a plain `usize` that is written only
        // by `try_push` before the block is published by the `next` CAS, so the `Acquire`
        // side of that CAS orders it before this read.
        debug_assert!(unsafe {
            ret.map_or(true, |block| {
                block.as_ref().header.start_index == self.header.start_index.wrapping_add(BLOCK_CAP)
            })
        });

        ret
    }

    /// Pushes `block` as the next block in the link.
    ///
    /// Returns Ok if successful, otherwise, a pointer to the next block in
    /// the list is returned.
    ///
    /// This requires that the next pointer is null.
    ///
    /// # Ordering
    ///
    /// This performs a compare-and-swap on `next` using `AcqRel` ordering.
    ///
    /// # Safety
    ///
    /// To maintain safety, the caller must ensure:
    ///
    /// * `block` is not freed until it has been removed from the list.
    pub(crate) unsafe fn try_push(
        &self,
        block: &mut NonNull<Block<T>>,
        success: Ordering,
        failure: Ordering,
    ) -> Result<(), NonNull<Block<T>>> {
        // SAFETY:
        // Operation: `block.as_mut()`, creating `&mut Block<T>`.
        // Contract from `NonNull::as_mut`: the pointer must be aligned, point to an
        // initialized `Block<T>`, be live for the returned lifetime, and be *unique* — no
        // other reference to that block may exist.
        // Evidence:
        // - Alignment, initialization and liveness: by this method's `# Safety`
        //   precondition the caller keeps `block` alive until it is removed from the list;
        //   every caller obtains it from `Box::into_raw(Block::new(..))`.
        // - Uniqueness: `block` is passed as `&mut NonNull<Block<T>>` from a caller that
        //   has not yet published it. The only publication is the `compare_exchange`
        //   below, which happens after this write; until then no other thread can reach
        //   the block, so this is the sole reference.
        // The write itself is a plain `usize` store, and ordering it before the CAS means
        // any thread that later acquires the block through `next` sees the correct
        // `start_index`.
        unsafe { block.as_mut() }.header.start_index =
            self.header.start_index.wrapping_add(BLOCK_CAP);

        let next_ptr = self
            .header
            .next
            .compare_exchange(ptr::null_mut(), block.as_ptr(), success, failure)
            .unwrap_or_else(|x| x);

        match NonNull::new(next_ptr) {
            Some(next_ptr) => Err(next_ptr),
            None => Ok(()),
        }
    }

    /// Grows the `Block` linked list by allocating and appending a new block.
    ///
    /// The next block in the linked list is returned. This may or may not be
    /// the one allocated by the function call.
    ///
    /// # Implementation
    ///
    /// It is assumed that `self.next` is null. A new block is allocated with
    /// `start_index` set to be the next block. A compare-and-swap is performed
    /// with `AcqRel` memory ordering. If the compare-and-swap is successful, the
    /// newly allocated block is released to other threads walking the block
    /// linked list. If the compare-and-swap fails, the current thread acquires
    /// the next block in the linked list, allowing the current thread to access
    /// the slots.
    pub(crate) fn grow(&self) -> NonNull<Block<T>> {
        // Create the new block. It is assumed that the block will become the
        // next one after `&self`. If this turns out to not be the case,
        // `start_index` is updated accordingly.
        let new_block = Block::new(self.header.start_index + BLOCK_CAP);

        // SAFETY:
        // Contract from `NonNull::new_unchecked`: the pointer must be non-null.
        // Evidence: `Box::into_raw` is documented to return a non-null pointer — `Box<T>`
        // itself has a validity invariant of being non-null, so the converted raw pointer
        // cannot be null.
        // Postcondition: ownership of the allocation has moved out of the `Box` and is now
        // held only by this raw pointer. From here it is either published into the list by
        // the CAS below (after which the receiver frees it) or handed to `try_push`, which
        // keeps the same obligation. Neither path drops it here, so there is no double
        // free and no leak on a successful push.
        let mut new_block = unsafe { NonNull::new_unchecked(Box::into_raw(new_block)) };

        // Attempt to store the block. The first compare-and-swap attempt is
        // "unrolled" due to minor differences in logic
        //
        // `AcqRel` is used as the ordering **only** when attempting the
        // compare-and-swap on self.next.
        //
        // If the compare-and-swap fails, then the actual value of the cell is
        // returned from this function and accessed by the caller. Given this,
        // the memory must be acquired.
        //
        // `Release` ensures that the newly allocated block is available to
        // other threads acquiring the next pointer.
        let next = NonNull::new(
            self.header
                .next
                .compare_exchange(ptr::null_mut(), new_block.as_ptr(), AcqRel, Acquire)
                .unwrap_or_else(|x| x),
        );

        let next = match next {
            Some(next) => next,
            None => {
                // The compare-and-swap succeeded and the newly allocated block
                // is successfully pushed.
                return new_block;
            }
        };

        // There already is a next block in the linked list. The newly allocated
        // block could be dropped and the discovered next block returned;
        // however, that would be wasteful. Instead, the linked list is walked
        // by repeatedly attempting to compare-and-swap the pointer into the
        // `next` register until the compare-and-swap succeed.
        //
        // Care is taken to update new_block's start_index field as appropriate.

        let mut curr = next;

        // TODO: Should this iteration be capped?
        loop {
            // SAFETY:
            // Two operations.
            // 1. `curr.as_ref()` — creating `&Block<T>`. Contract: aligned, initialized,
            //    live for the returned lifetime, no `&mut` alias. Evidence: `curr` came
            //    either from the `next` CAS above or from a previous `try_push` failure,
            //    both of which return pointers that were published into the list from
            //    `Box::into_raw(Block::new(..))`, hence aligned and initialized. Blocks
            //    are freed only by the receiver after being unlinked, and this walk starts
            //    from a block reachable from `&self`, which the caller keeps borrowed, so
            //    every block it reaches is still linked. The only `&mut Block<T>`
            //    (`reclaim`) requires unique ownership of an unlinked block.
            // 2. `try_push(..)` — contract: `block` must not be freed until it has been
            //    removed from the list. Evidence: `new_block` is the raw pointer whose
            //    ownership we took above; nothing in this function frees it, and once the
            //    CAS succeeds it is in the list, so its lifetime is the receiver's
            //    responsibility from then on.
            let actual = unsafe { curr.as_ref().try_push(&mut new_block, AcqRel, Acquire) };

            curr = match actual {
                Ok(()) => {
                    return next;
                }
                Err(curr) => curr,
            };

            crate::loom::thread::yield_now();
        }
    }
}

/// Returns `true` if the specified slot has a value ready to be consumed.
fn is_ready(bits: usize, slot: usize) -> bool {
    let mask = 1 << slot;
    mask == mask & bits
}

/// Returns `true` if the closed flag has been set.
fn is_tx_closed(bits: usize) -> bool {
    TX_CLOSED == bits & TX_CLOSED
}

impl<T> Values<T> {
    /// Initialize a `Values` struct from a pointer.
    ///
    /// # Safety
    ///
    /// The raw pointer must be valid for writing a `Values<T>`.
    unsafe fn initialize(_value: NonNull<Values<T>>) {
        // When fuzzing, `UnsafeCell` needs to be initialized.
        if_loom! {
            let p = _value.as_ptr() as *mut UnsafeCell<MaybeUninit<T>>;
            for i in 0..BLOCK_CAP {
                unsafe {
                    p.add(i).write(UnsafeCell::new(MaybeUninit::uninit()));
                }
            }
        }
    }
}

impl<T> ops::Index<usize> for Values<T> {
    type Output = UnsafeCell<MaybeUninit<T>>;

    fn index(&self, index: usize) -> &Self::Output {
        self.0.index(index)
    }
}

#[cfg(all(test, not(loom)))]
#[test]
fn assert_no_stack_overflow() {
    // https://github.com/tokio-rs/tokio/issues/5293

    struct Foo {
        _a: [u8; 2_000_000],
    }

    assert_eq!(
        Layout::new::<MaybeUninit<Block<Foo>>>(),
        Layout::new::<Block<Foo>>()
    );

    let _block = Block::<Foo>::new(0);
}
